PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE `core_store` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `key` varchar(255) null, `value` longtext null, `type` varchar(255) null, `environment` varchar(255) null, `tag` varchar(255) null);
INSERT INTO core_store VALUES(1,'db_model_core_store','{"key":{"type":"string"},"value":{"type":"text"},"type":{"type":"string"},"environment":{"type":"string"},"tag":{"type":"string"}}','object',NULL,NULL);
INSERT INTO core_store VALUES(2,'db_model_strapi_administrator','{"username":{"type":"string","minLength":3,"unique":true,"configurable":false,"required":true},"email":{"type":"email","minLength":6,"configurable":false,"required":true},"password":{"type":"password","minLength":6,"configurable":false,"private":true,"required":true},"resetPasswordToken":{"type":"string","configurable":false,"private":true},"blocked":{"type":"boolean","default":false,"configurable":false}}','object',NULL,NULL);
INSERT INTO core_store VALUES(3,'db_model_users-permissions_permission','{"type":{"type":"string","required":true,"configurable":false},"controller":{"type":"string","required":true,"configurable":false},"action":{"type":"string","required":true,"configurable":false},"enabled":{"type":"boolean","required":true,"configurable":false},"policy":{"type":"string","configurable":false},"role":{"model":"role","via":"permissions","plugin":"users-permissions","configurable":false}}','object',NULL,NULL);
INSERT INTO core_store VALUES(4,'db_model_users-permissions_role','{"name":{"type":"string","minLength":3,"required":true,"configurable":false},"description":{"type":"string","configurable":false},"type":{"type":"string","unique":true,"configurable":false},"permissions":{"collection":"permission","via":"role","plugin":"users-permissions","configurable":false,"isVirtual":true},"users":{"collection":"user","via":"role","configurable":false,"plugin":"users-permissions","isVirtual":true}}','object',NULL,NULL);
INSERT INTO core_store VALUES(5,'db_model_users-permissions_user','{"username":{"type":"string","minLength":3,"unique":true,"configurable":false,"required":true},"email":{"type":"email","minLength":6,"configurable":false,"required":true},"provider":{"type":"string","configurable":false},"password":{"type":"password","minLength":6,"configurable":false,"private":true},"resetPasswordToken":{"type":"string","configurable":false,"private":true},"confirmed":{"type":"boolean","default":false,"configurable":false},"blocked":{"type":"boolean","default":false,"configurable":false},"role":{"model":"role","via":"users","plugin":"users-permissions","configurable":false},"created_at":{"type":"timestamp"},"updated_at":{"type":"timestampUpdate"}}','object',NULL,NULL);
INSERT INTO core_store VALUES(6,'db_model_upload_file','{"name":{"type":"string","configurable":false,"required":true},"hash":{"type":"string","configurable":false,"required":true},"sha256":{"type":"string","configurable":false},"ext":{"type":"string","configurable":false},"mime":{"type":"string","configurable":false,"required":true},"size":{"type":"string","configurable":false,"required":true},"url":{"type":"string","configurable":false,"required":true},"provider":{"type":"string","configurable":false,"required":true},"provider_metadata":{"type":"json","configurable":false},"related":{"collection":"*","filter":"field","configurable":false},"created_at":{"type":"timestamp"},"updated_at":{"type":"timestampUpdate"}}','object',NULL,NULL);
INSERT INTO core_store VALUES(7,'db_model_upload_file_morph','{"upload_file_id":{"type":"integer"},"related_id":{"type":"integer"},"related_type":{"type":"text"},"field":{"type":"text"}}','object',NULL,NULL);
INSERT INTO core_store VALUES(8,'plugin_email_provider','{"provider":"sendmail","name":"Sendmail","auth":{"sendmail_default_from":{"label":"Sendmail Default From","type":"text"},"sendmail_default_replyto":{"label":"Sendmail Default Reply-To","type":"text"}}}','object','development','');
INSERT INTO core_store VALUES(9,'plugin_upload_provider','{"provider":"local","name":"Local server","enabled":true,"sizeLimit":1000000}','object','development','');
INSERT INTO core_store VALUES(10,'plugin_users-permissions_grant','{"email":{"enabled":true,"icon":"envelope"},"discord":{"enabled":false,"icon":"comments","key":"","secret":"","callback":"/auth/discord/callback","scope":["identify","email"]},"facebook":{"enabled":false,"icon":"facebook-official","key":"","secret":"","callback":"/auth/facebook/callback","scope":["email"]},"google":{"enabled":false,"icon":"google","key":"","secret":"","callback":"/auth/google/callback","scope":["email"]},"github":{"enabled":false,"icon":"github","key":"","secret":"","redirect_uri":"/auth/github/callback","scope":["user","user:email"]},"microsoft":{"enabled":false,"icon":"windows","key":"","secret":"","callback":"/auth/microsoft/callback","scope":["user.read"]},"twitter":{"enabled":false,"icon":"twitter","key":"","secret":"","callback":"/auth/twitter/callback"},"instagram":{"enabled":false,"icon":"instagram","key":"","secret":"","callback":"/auth/instagram/callback"}}','object','','');
INSERT INTO core_store VALUES(11,'plugin_content_manager_configuration_content_types::admin.administrator','{"uid":"administrator","source":"admin","settings":{"searchable":true,"filterable":true,"bulkable":true,"pageSize":10,"mainField":"username","defaultSortBy":"username","defaultSortOrder":"ASC"},"metadatas":{"id":{"edit":{},"list":{"label":"Id","searchable":true,"sortable":true}},"username":{"edit":{"label":"Username","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Username","searchable":true,"sortable":true}},"email":{"edit":{"label":"Email","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Email","searchable":true,"sortable":true}},"password":{"edit":{"label":"Password","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Password","searchable":true,"sortable":true}},"resetPasswordToken":{"edit":{"label":"ResetPasswordToken","description":"","placeholder":"","visible":false,"editable":true},"list":{"label":"ResetPasswordToken","searchable":true,"sortable":true}},"blocked":{"edit":{"label":"Blocked","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Blocked","searchable":true,"sortable":true}}},"layouts":{"list":["id","username","email","resetPasswordToken"],"edit":[[{"name":"username","size":6},{"name":"email","size":6}],[{"name":"password","size":6},{"name":"resetPasswordToken","size":6}],[{"name":"blocked","size":4}]],"editRelations":[]}}','object','','');
INSERT INTO core_store VALUES(12,'plugin_users-permissions_email','{"reset_password":{"display":"Email.template.reset_password","icon":"refresh","options":{"from":{"name":"Administration Panel","email":"no-reply@strapi.io"},"response_email":"","object":"­Reset password","message":"<p>We heard that you lost your password. Sorry about that!</p>\n\n<p>But don’t worry! You can use the following link to reset your password:</p>\n\n<p><%= URL %>?code=<%= TOKEN %></p>\n\n<p>Thanks.</p>"}},"email_confirmation":{"display":"Email.template.email_confirmation","icon":"check-square-o","options":{"from":{"name":"Administration Panel","email":"no-reply@strapi.io"},"response_email":"","object":"Account confirmation","message":"<p>Thank you for registering!</p>\n\n<p>You have to confirm your email address. Please click on the link below.</p>\n\n<p><%= URL %>?confirmation=<%= CODE %></p>\n\n<p>Thanks.</p>"}}}','object','','');
INSERT INTO core_store VALUES(13,'plugin_content_manager_configuration_content_types::users-permissions.permission','{"uid":"permission","source":"users-permissions","settings":{"searchable":true,"filterable":true,"bulkable":true,"pageSize":10,"mainField":"type","defaultSortBy":"type","defaultSortOrder":"ASC"},"metadatas":{"id":{"edit":{},"list":{"label":"Id","searchable":true,"sortable":true}},"type":{"edit":{"label":"Type","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Type","searchable":true,"sortable":true}},"controller":{"edit":{"label":"Controller","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Controller","searchable":true,"sortable":true}},"action":{"edit":{"label":"Action","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Action","searchable":true,"sortable":true}},"enabled":{"edit":{"label":"Enabled","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Enabled","searchable":true,"sortable":true}},"policy":{"edit":{"label":"Policy","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Policy","searchable":true,"sortable":true}},"role":{"edit":{"label":"Role","description":"","placeholder":"","visible":true,"editable":true,"mainField":"name"},"list":{"label":"Role","searchable":false,"sortable":false}}},"layouts":{"list":["id","type","controller","action"],"edit":[[{"name":"type","size":6},{"name":"controller","size":6}],[{"name":"action","size":6},{"name":"enabled","size":4}],[{"name":"policy","size":6}]],"editRelations":["role"]}}','object','','');
INSERT INTO core_store VALUES(14,'plugin_content_manager_configuration_content_types::users-permissions.role','{"uid":"role","source":"users-permissions","settings":{"searchable":true,"filterable":true,"bulkable":true,"pageSize":10,"mainField":"name","defaultSortBy":"name","defaultSortOrder":"ASC"},"metadatas":{"id":{"edit":{},"list":{"label":"Id","searchable":true,"sortable":true}},"name":{"edit":{"label":"Name","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Name","searchable":true,"sortable":true}},"description":{"edit":{"label":"Description","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Description","searchable":true,"sortable":true}},"type":{"edit":{"label":"Type","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Type","searchable":true,"sortable":true}},"permissions":{"edit":{"label":"Permissions","description":"","placeholder":"","visible":true,"editable":true,"mainField":"type"},"list":{"label":"Permissions","searchable":false,"sortable":false}},"users":{"edit":{"label":"Users","description":"","placeholder":"","visible":true,"editable":true,"mainField":"username"},"list":{"label":"Users","searchable":false,"sortable":false}}},"layouts":{"list":["id","name","description","type"],"edit":[[{"name":"name","size":6},{"name":"description","size":6}],[{"name":"type","size":6}]],"editRelations":["permissions","users"]}}','object','','');
INSERT INTO core_store VALUES(15,'plugin_content_manager_configuration_content_types::upload.file','{"uid":"file","source":"upload","settings":{"searchable":true,"filterable":true,"bulkable":true,"pageSize":10,"mainField":"name","defaultSortBy":"name","defaultSortOrder":"ASC"},"metadatas":{"id":{"edit":{},"list":{"label":"Id","searchable":true,"sortable":true}},"name":{"edit":{"label":"Name","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Name","searchable":true,"sortable":true}},"hash":{"edit":{"label":"Hash","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Hash","searchable":true,"sortable":true}},"sha256":{"edit":{"label":"Sha256","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Sha256","searchable":true,"sortable":true}},"ext":{"edit":{"label":"Ext","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Ext","searchable":true,"sortable":true}},"mime":{"edit":{"label":"Mime","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Mime","searchable":true,"sortable":true}},"size":{"edit":{"label":"Size","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Size","searchable":true,"sortable":true}},"url":{"edit":{"label":"Url","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Url","searchable":true,"sortable":true}},"provider":{"edit":{"label":"Provider","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Provider","searchable":true,"sortable":true}},"provider_metadata":{"edit":{"label":"Provider_metadata","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Provider_metadata","searchable":false,"sortable":false}},"related":{"edit":{"label":"Related","description":"","placeholder":"","visible":true,"editable":true,"mainField":"id"},"list":{"label":"Related","searchable":false,"sortable":false}},"created_at":{"edit":{"label":"Created_at","description":"","placeholder":"","visible":false,"editable":true},"list":{"label":"Created_at","searchable":true,"sortable":true}},"updated_at":{"edit":{"label":"Updated_at","description":"","placeholder":"","visible":false,"editable":true},"list":{"label":"Updated_at","searchable":true,"sortable":true}}},"layouts":{"list":["id","name","hash","sha256"],"edit":[[{"name":"name","size":6},{"name":"hash","size":6}],[{"name":"sha256","size":6},{"name":"ext","size":6}],[{"name":"mime","size":6},{"name":"size","size":6}],[{"name":"url","size":6},{"name":"provider","size":6}],[{"name":"provider_metadata","size":12}]],"editRelations":["related"]}}','object','','');
INSERT INTO core_store VALUES(16,'plugin_content_manager_configuration_content_types::users-permissions.user','{"uid":"user","source":"users-permissions","settings":{"searchable":true,"filterable":true,"bulkable":true,"pageSize":10,"mainField":"username","defaultSortBy":"username","defaultSortOrder":"ASC"},"metadatas":{"id":{"edit":{},"list":{"label":"Id","searchable":true,"sortable":true}},"username":{"edit":{"label":"Username","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Username","searchable":true,"sortable":true}},"email":{"edit":{"label":"Email","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Email","searchable":true,"sortable":true}},"provider":{"edit":{"label":"Provider","description":"","placeholder":"","visible":false,"editable":true},"list":{"label":"Provider","searchable":true,"sortable":true}},"password":{"edit":{"label":"Password","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Password","searchable":true,"sortable":true}},"resetPasswordToken":{"edit":{"label":"ResetPasswordToken","description":"","placeholder":"","visible":false,"editable":true},"list":{"label":"ResetPasswordToken","searchable":true,"sortable":true}},"confirmed":{"edit":{"label":"Confirmed","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Confirmed","searchable":true,"sortable":true}},"blocked":{"edit":{"label":"Blocked","description":"","placeholder":"","visible":true,"editable":true},"list":{"label":"Blocked","searchable":true,"sortable":true}},"role":{"edit":{"label":"Role","description":"","placeholder":"","visible":true,"editable":true,"mainField":"name"},"list":{"label":"Role","searchable":false,"sortable":false}},"created_at":{"edit":{"label":"Created_at","description":"","placeholder":"","visible":false,"editable":true},"list":{"label":"Created_at","searchable":true,"sortable":true}},"updated_at":{"edit":{"label":"Updated_at","description":"","placeholder":"","visible":false,"editable":true},"list":{"label":"Updated_at","searchable":true,"sortable":true}}},"layouts":{"list":["id","username","email","provider"],"edit":[[{"name":"username","size":6},{"name":"email","size":6}],[{"name":"provider","size":6},{"name":"password","size":6}],[{"name":"resetPasswordToken","size":6},{"name":"confirmed","size":4}],[{"name":"blocked","size":4}]],"editRelations":["role"]}}','object','','');
INSERT INTO core_store VALUES(17,'plugin_users-permissions_advanced','{"unique_email":true,"allow_register":true,"email_confirmation":false,"email_confirmation_redirection":"http://localhost:1337/admin","email_reset_password":"http://localhost:1337/admin","default_role":"authenticated"}','object','','');
CREATE TABLE `strapi_administrator` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `username` varchar(255) not null, `email` varchar(255) not null, `password` varchar(255) not null, `resetPasswordToken` varchar(255) null, `blocked` boolean null);
INSERT INTO strapi_administrator VALUES(1,'dhadd','juylitalo@gmail.com','$2a$10$WZcrWxGDPwqwsd/tOkiCIuAnyxJAAlBRpQQJmCANxW5hxn0y9tLkK',NULL,NULL);
CREATE TABLE `users-permissions_permission` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `type` varchar(255) not null, `controller` varchar(255) not null, `action` varchar(255) not null, `enabled` boolean not null, `policy` varchar(255) null, `role` integer null);
INSERT INTO "users-permissions_permission" VALUES(1,'content-type-builder','contenttypebuilder','getmodels',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(2,'content-type-builder','contenttypebuilder','getmodel',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(3,'content-type-builder','contenttypebuilder','getconnections',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(4,'content-type-builder','contenttypebuilder','createmodel',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(5,'content-type-builder','contenttypebuilder','updatemodel',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(6,'content-type-builder','contenttypebuilder','deletemodel',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(7,'content-type-builder','groups','getgroups',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(8,'content-type-builder','groups','getgroup',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(9,'content-type-builder','groups','creategroup',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(10,'content-type-builder','groups','updategroup',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(11,'content-type-builder','groups','deletegroup',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(12,'content-manager','contentmanager','find',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(13,'content-manager','contentmanager','findone',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(14,'content-manager','contentmanager','count',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(15,'content-manager','contentmanager','create',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(16,'content-manager','contentmanager','update',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(17,'content-manager','contentmanager','delete',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(18,'content-manager','contentmanager','deletemany',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(19,'content-manager','contenttypes','listcontenttypes',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(20,'content-manager','contenttypes','findcontenttype',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(21,'content-manager','contenttypes','updatecontenttype',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(22,'content-manager','generalsettings','getgeneralsettings',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(23,'content-manager','generalsettings','updategeneralsettings',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(24,'content-manager','groups','listgroups',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(25,'content-manager','groups','findgroup',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(26,'content-manager','groups','updategroup',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(27,'users-permissions','auth','callback',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(28,'users-permissions','auth','changepassword',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(29,'users-permissions','auth','connect',1,'',1);
INSERT INTO "users-permissions_permission" VALUES(30,'users-permissions','auth','forgotpassword',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(31,'users-permissions','auth','register',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(32,'users-permissions','auth','emailconfirmation',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(33,'users-permissions','user','find',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(34,'users-permissions','user','me',1,'',1);
INSERT INTO "users-permissions_permission" VALUES(35,'users-permissions','user','findone',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(36,'users-permissions','user','create',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(37,'users-permissions','user','update',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(38,'users-permissions','user','destroy',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(39,'users-permissions','user','destroyall',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(40,'users-permissions','userspermissions','createrole',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(41,'users-permissions','userspermissions','deleteprovider',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(42,'users-permissions','userspermissions','deleterole',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(43,'users-permissions','userspermissions','getpermissions',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(44,'users-permissions','userspermissions','getpolicies',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(45,'users-permissions','userspermissions','getrole',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(46,'users-permissions','userspermissions','getroles',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(47,'users-permissions','userspermissions','getroutes',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(48,'users-permissions','userspermissions','index',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(49,'users-permissions','userspermissions','init',1,'',1);
INSERT INTO "users-permissions_permission" VALUES(50,'users-permissions','userspermissions','searchusers',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(51,'users-permissions','userspermissions','updaterole',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(52,'users-permissions','userspermissions','getemailtemplate',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(53,'users-permissions','userspermissions','updateemailtemplate',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(54,'users-permissions','userspermissions','getadvancedsettings',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(55,'users-permissions','userspermissions','updateadvancedsettings',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(56,'users-permissions','userspermissions','getproviders',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(57,'users-permissions','userspermissions','updateproviders',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(58,'email','email','send',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(59,'email','email','getenvironments',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(60,'email','email','getsettings',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(61,'email','email','updatesettings',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(62,'upload','upload','upload',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(63,'upload','upload','getenvironments',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(64,'upload','upload','getsettings',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(65,'upload','upload','updatesettings',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(66,'upload','upload','find',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(67,'upload','upload','findone',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(68,'upload','upload','count',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(69,'upload','upload','destroy',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(70,'upload','upload','search',0,'',1);
INSERT INTO "users-permissions_permission" VALUES(71,'content-type-builder','contenttypebuilder','getmodels',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(72,'content-type-builder','contenttypebuilder','getmodel',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(73,'content-type-builder','contenttypebuilder','getconnections',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(74,'content-type-builder','contenttypebuilder','createmodel',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(75,'content-type-builder','contenttypebuilder','updatemodel',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(76,'content-type-builder','contenttypebuilder','deletemodel',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(77,'content-type-builder','groups','getgroups',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(78,'content-type-builder','groups','getgroup',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(79,'content-type-builder','groups','creategroup',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(80,'content-type-builder','groups','updategroup',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(81,'content-type-builder','groups','deletegroup',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(82,'content-manager','contentmanager','find',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(83,'content-manager','contentmanager','findone',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(84,'content-manager','contentmanager','count',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(85,'content-manager','contentmanager','create',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(86,'content-manager','contentmanager','update',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(87,'content-manager','contentmanager','delete',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(88,'content-manager','contentmanager','deletemany',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(89,'content-manager','contenttypes','listcontenttypes',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(90,'content-manager','contenttypes','findcontenttype',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(91,'content-manager','contenttypes','updatecontenttype',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(92,'content-manager','generalsettings','getgeneralsettings',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(93,'content-manager','generalsettings','updategeneralsettings',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(94,'content-manager','groups','listgroups',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(95,'content-manager','groups','findgroup',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(96,'content-manager','groups','updategroup',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(97,'users-permissions','auth','callback',1,'',2);
INSERT INTO "users-permissions_permission" VALUES(98,'users-permissions','auth','changepassword',1,'',2);
INSERT INTO "users-permissions_permission" VALUES(99,'users-permissions','auth','connect',1,'',2);
INSERT INTO "users-permissions_permission" VALUES(100,'users-permissions','auth','forgotpassword',1,'',2);
INSERT INTO "users-permissions_permission" VALUES(101,'users-permissions','auth','register',1,'',2);
INSERT INTO "users-permissions_permission" VALUES(102,'users-permissions','auth','emailconfirmation',1,'',2);
INSERT INTO "users-permissions_permission" VALUES(103,'users-permissions','user','find',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(104,'users-permissions','user','me',1,'',2);
INSERT INTO "users-permissions_permission" VALUES(105,'users-permissions','user','findone',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(106,'users-permissions','user','create',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(107,'users-permissions','user','update',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(108,'users-permissions','user','destroy',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(109,'users-permissions','user','destroyall',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(110,'users-permissions','userspermissions','createrole',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(111,'users-permissions','userspermissions','deleteprovider',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(112,'users-permissions','userspermissions','deleterole',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(113,'users-permissions','userspermissions','getpermissions',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(114,'users-permissions','userspermissions','getpolicies',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(115,'users-permissions','userspermissions','getrole',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(116,'users-permissions','userspermissions','getroles',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(117,'users-permissions','userspermissions','getroutes',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(118,'users-permissions','userspermissions','index',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(119,'users-permissions','userspermissions','init',1,'',2);
INSERT INTO "users-permissions_permission" VALUES(120,'users-permissions','userspermissions','searchusers',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(121,'users-permissions','userspermissions','updaterole',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(122,'users-permissions','userspermissions','getemailtemplate',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(123,'users-permissions','userspermissions','updateemailtemplate',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(124,'users-permissions','userspermissions','getadvancedsettings',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(125,'users-permissions','userspermissions','updateadvancedsettings',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(126,'users-permissions','userspermissions','getproviders',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(127,'users-permissions','userspermissions','updateproviders',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(128,'email','email','send',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(129,'email','email','getenvironments',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(130,'email','email','getsettings',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(131,'email','email','updatesettings',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(132,'upload','upload','upload',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(133,'upload','upload','getenvironments',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(134,'upload','upload','getsettings',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(135,'upload','upload','updatesettings',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(136,'upload','upload','find',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(137,'upload','upload','findone',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(138,'upload','upload','count',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(139,'upload','upload','destroy',0,'',2);
INSERT INTO "users-permissions_permission" VALUES(140,'upload','upload','search',0,'',2);
CREATE TABLE `users-permissions_role` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `name` varchar(255) not null, `description` varchar(255) null, `type` varchar(255) null);
INSERT INTO "users-permissions_role" VALUES(1,'Authenticated','Default role given to authenticated user.','authenticated');
INSERT INTO "users-permissions_role" VALUES(2,'Public','Default role given to unauthenticated user.','public');
CREATE TABLE `users-permissions_user` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `username` varchar(255) not null, `email` varchar(255) not null, `provider` varchar(255) null, `password` varchar(255) null, `resetPasswordToken` varchar(255) null, `confirmed` boolean null, `blocked` boolean null, `role` integer null, `created_at` timestamp DEFAULT CURRENT_TIMESTAMP null, `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP null);
CREATE TABLE `upload_file` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `name` varchar(255) not null, `hash` varchar(255) not null, `sha256` varchar(255) null, `ext` varchar(255) null, `mime` varchar(255) not null, `size` varchar(255) not null, `url` varchar(255) not null, `provider` varchar(255) not null, `provider_metadata` longtext null, `created_at` timestamp DEFAULT CURRENT_TIMESTAMP null, `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP null);
CREATE TABLE `upload_file_morph` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `upload_file_id` int null, `related_id` int null, `related_type` longtext null, `field` longtext null);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('core_store',17);
INSERT INTO sqlite_sequence VALUES('users-permissions_role',2);
INSERT INTO sqlite_sequence VALUES('users-permissions_permission',140);
INSERT INTO sqlite_sequence VALUES('strapi_administrator',1);
CREATE UNIQUE INDEX `strapi_administrator_username_unique` on `strapi_administrator` (`username`);
CREATE UNIQUE INDEX `users-permissions_role_type_unique` on `users-permissions_role` (`type`);
CREATE UNIQUE INDEX `users-permissions_user_username_unique` on `users-permissions_user` (`username`);
COMMIT;
